# Generated by Django 3.0.5 on 2020-05-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFFIU_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
