# Generated by Django 3.0.5 on 2020-05-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JFFIU_app', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
