# Generated by Django 3.0.5 on 2020-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFFIU_app', '0003_auto_20200518_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
