# Generated by Django 3.0.5 on 2020-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFFIU_app', '0004_auto_20200518_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Vietnam', max_length=100),
        ),
    ]
